Repository vortexntnu/vortex-auv, pull requests merged in 2021-02, with the labels that each got.

#151 Adds zed ros wrapper to auv.launch
  README.md
  auv_setup/launch/auv.launch
Labels: Perception

#152 Feature/pc launch for joystick
  auv_setup/README.md
  auv_setup/config/robots/gladlaks.yaml
  auv_setup/config/robots/manta_enu.yaml
  auv_setup/launch/auv.launch
  auv_setup/launch/gladlaks.launch
  auv_setup/launch/manta.launch
  auv_setup/launch/pc.launch
  auv_setup/launch/rov.launch
  motion/guidance_interface/src/guidance_interface.py
  motion/joystick_guidance/README.md
  motion/joystick_guidance/scripts/joystick_guidance.py
  motion/joystick_topside/CMakeLists.txt
  motion/joystick_topside/README.md
  motion/joystick_topside/package.xml
  motion/joystick_topside/scripts/joystick_topside.py
  motion/los_guidance/scripts/los_guidance_backstepping.py
  motion/motion_launch/launch/motion.launch
  navigation/navigation_launch/launch/navigation.launch
Labels: Control, enhancement

#169 Battery monitor
  auv_setup/config/robots/gladlaks.yaml
  mission/battery_monitor/README.md
  mission/battery_monitor/launch/battery_monitor.launch
  mission/battery_monitor/src/battery_monitor.py
Labels: Perception

#161 improvement/pc_launch_guide
  README.md
  auv_setup/README.md
Labels: Control

#173 Feature/xavier-mcu_interface
  auv_setup/launch/gladlaks.launch
  motion/guidance_interface/src/guidance_interface.py
  motion/motion_launch/launch/motion.launch
  motion/thruster_allocator/src/allocator_ros.cpp
Labels: Control

#175 Delete motion/mcu_interface directory
  motion/mcu_interface/CMakeLists.txt
  motion/mcu_interface/README.md
  motion/mcu_interface/include/McuInterface.h
  motion/mcu_interface/include/crc.h
  motion/mcu_interface/package.xml
  motion/mcu_interface/src/McuInterface.cpp
  motion/mcu_interface/src/crc.c
  motion/mcu_interface/src/mcu_interface_node.cpp
Labels: refactor
