Repository vortexntnu/vortex-auv, pull requests merged in 2025-02, with the labels that each got.

#518 Move common topic definitions to orca.yaml
  acoustics/acoustics_data_record/CMakeLists.txt
  acoustics/acoustics_data_record_auv/CMakeLists.txt
  acoustics/acoustics_data_record_auv/README
  acoustics/acoustics_data_record_auv/acoustics_data_record_auv/__init__.py
  acoustics/acoustics_data_record_auv/acoustics_data_record_auv/acoustics_data_record_lib.py
  acoustics/acoustics_data_record_auv/acoustics_data_record_auv/acoustics_data_record_node.py
  acoustics/acoustics_data_record_auv/launch/acoustics_data_record_launch.py
  acoustics/acoustics_data_record_auv/package.xml
  acoustics/acoustics_data_record_auv/utilities/display_acoustics_data_live.py
  acoustics/acoustics_interface/CMakeLists.txt
  acoustics/acoustics_interface/launch/__init__.py
  acoustics/acoustics_interface_auv/CMakeLists.txt
  acoustics/acoustics_interface_auv/README
  acoustics/acoustics_interface_auv/acoustics_interface_auv/__init__.py
  acoustics/acoustics_interface_auv/acoustics_interface_auv/acoustics_interface_lib.py
  acoustics/acoustics_interface_auv/acoustics_interface_auv/acoustics_interface_node.py
  acoustics/acoustics_interface_auv/launch/acoustics_interface_launch.py
  acoustics/acoustics_interface_auv/package.xml
  auv_setup/config/robots/orca.yaml
  control/velocity_controller_lqr/config/param_velocity_controller_lqr.yaml
  control/velocity_controller_lqr/launch/velocity_controller_lqr.launch.py
  control/velocity_controller_lqr/scripts/velocity_controller_lqr_node.py
  mission/blackbox/CMakeLists.txt
  mission/blackbox/blackbox/__init__.py
  mission/blackbox_auv/CMakeLists.txt
  mission/blackbox_auv/README
  mission/blackbox_auv/blackbox_auv/__init__.py
  mission/blackbox_auv/blackbox_auv/blackbox_log_data.py
  mission/blackbox_auv/blackbox_auv/blackbox_node.py
  mission/blackbox_auv/blackbox_data/.gitignore
  mission/blackbox_auv/launch/blackbox.launch.py
  mission/blackbox_auv/package.xml
  mission/blackbox_auv/startup_scripts/blackbox.service
  mission/blackbox_auv/startup_scripts/blackbox.sh
  mission/internal_status_auv/internal_status_auv/power_sense_module_node.py
  mission/internal_status_auv/internal_status_auv/pressure_sensor_lib.py
  mission/internal_status_auv/internal_status_auv/pressure_sensor_node.py
  mission/internal_status_auv/internal_status_auv/temperature_sensor_lib.py
  mission/internal_status_auv/internal_status_auv/temperature_sensor_node.py
  mission/internal_status_auv/launch/internal_status_auv.launch.py
  mission/joystick_interface_auv/config/param_joystick_interface_auv.yaml
  mission/joystick_interface_auv/joystick_interface_auv/joystick_interface_auv_node.py
  mission/joystick_interface_auv/launch/joystick_interface_auv.launch.py
  motion/thrust_allocator_auv/CMakeLists.txt
  motion/thrust_allocator_auv/include/thrust_allocator_auv/thrust_allocator_ros.hpp
  motion/thrust_allocator_auv/include/thrust_allocator_auv/thrust_allocator_utils.hpp
  motion/thrust_allocator_auv/launch/thrust_allocator_auv.launch.py
  motion/thrust_allocator_auv/package.xml
  motion/thrust_allocator_auv/src/thrust_allocator_ros.cpp
  motion/thruster_interface_auv/CMakeLists.txt
  motion/thruster_interface_auv/README.md
  motion/thruster_interface_auv/config/thruster_interface_auv_config.yaml
  motion/thruster_interface_auv/src/thruster_interface_auv_ros.cpp
Labels: refactor, AUV

#525 ci/code-coverage
  .github/workflows/code-coverage.yml
  README.md
  codecov.yml
Labels: feature, DevOps

#527 fix/docker
  README.md
  docker/Dockerfile
  entrypoint.sh
Labels: bug, refactor, AUV
